name: Appium Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [34]
        target: [google_apis]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - uses: actions/setup-node@v4.3.0
      with:
        node-version: '22.11.0'
    - run: |
            npm install -g appium
            appium driver install uiautomator2

    - name: Start Android Emulator
      uses: ReactiveCircus/android-emulator-runner@v2.33.0
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        disable-animations: true
        script: echo "Emulator started"

    - name: Wait for ADB device
      run: |
        echo "Waiting for emulator to be ready..."
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
        adb devices
        echo "Emulator is ready!"

    - name: Start Appium
      run: |
            appium &>/dev/null &
            sleep 10

    - name: Run Appium Tests
      run: mvn clean test -P android
