name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [25]
        target: [default]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: '22.11.0'
      - run: |
          npm install -g appium@v1.20.2
          appium -v
          appium &>/dev/null &
      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: mvn clean test -Pandroid